#!/bin/bash

# Set UID/PID of user that youtube-dl will be run as
YOUTUBEDLPGID=${PGID:65536}
YOUTUBEDLPUID=${PUID:1027}

# Create dockeruser user/group
addgroup -g $YOUTUBEDLPGID dockeruser
adduser -D -u $YOUTUBEDLPUID -G dockeruser -h /home/dockeruser dockeruser
chown $YOUTUBEDLPUID:$YOUTUBEDLPGID /home/dockeruser
chown $YOUTUBEDLPUID:$YOUTUBEDLPGID /usr/local/bin/youtube-dl
chmod u+s /usr/local/bin/youtube-dl
export HOME=/home/dockeruser

# Run youtube-dl with remainder of command line arguments
su-exec dockeruser:dockeruser /usr/local/bin/youtube-dl "$@"

